<HomeScreen>:
    FloatLayout:
        # 1. Achtergrond (Beige/Crème achtergrond)
        canvas.before:
            Color:
                rgba: 244/255, 239/255, 230/255, 1
            Rectangle:
                pos: self.pos
                size: self.size

        # 2. Hoofdtitel
        Label:
            text: "Stadsmuseum Veenendaal"
            font_name: "assets/fonts/Chalet NewYorkNineteenEighty.otf"
            font_size: "30sp"
            color: 125/255, 67/255, 53/255, 1
            size_hint: 0.8, 0.15
            pos_hint: {"center_x": 0.5, "center_y": 0.55}

        # 3. Admin-icoon (rechtsboven)
        Button:
            size_hint: None, None
            size: "55dp", "55dp"
            pos_hint: {"right": 0.97, "top": 0.97}
            background_normal: "assets/objects_img/logo/management.png"
            background_down: "assets/objects_img/logo/management.png"
            background_color: 1, 1, 1, 1
            border: 0, 0, 0, 0
            on_release: root.go_to_admin()